name: "Firewalk CI"

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - '*'

jobs:
  spm:
    name: Test with SPM
    runs-on: macOS-latest    
    env: 
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: SPM Test
        run: swift test -c debug --sanitize=thread
