name: "Firewalk CI"

on:
  push:
    branches: 
      - master
    paths:
      - 'Sources/**'
      - 'Tests/**'
      - '.github/workflows/**'
      - 'Package.swift'
  pull_request:
    paths:
      - 'Sources/**'
      - 'Tests/**'
      - '.github/workflows/**'
      - 'Package.swift'

concurrency: 
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  macOS:
    name: macOS
    runs-on: firebreak
    defaults:
      run:
        shell: "/usr/bin/arch -arch arm64e /bin/zsh {0}"
    env: 
      DEVELOPER_DIR: /Applications/Xcode_13.3.1.app/Contents/Developer
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: SPM Test
        run: swift test -c debug --sanitize=thread
  Linux:
    name: Linux
    runs-on: ubuntu-20.04
    container:
      image: swift:5.6.1-focal
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: SPM Linux Test
        run:  swift test -c debug
  Linux_Nightly:
    name: Linux Nightly
    runs-on: ubuntu-20.04
    container:
      image: swiftlang/swift:nightly-focal
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: SPM Linux Test
        run:  swift test -c debug
