name: "Firewalk CI"

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/**"
      - "Package.swift"
      - "Sources/**"
      - "Tests/**"
  pull_request:
    paths:
      - ".github/workflows/**"
      - "Package.swift"
      - "Sources/**"
      - "Tests/**"

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  macOS:
    name: macOS
    runs-on: firebreak
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: SPM Test
        run: swift test -c debug --sanitize=thread
  Linux:
    name: Linux
    runs-on: ubuntu-latest
    container:
      image: swift:5.9.0-jammy
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: SPM Linux Test
        run: swift test -c debug
  Linux_Nightly:
    name: Linux Nightly
    runs-on: ubuntu-latest
    container:
      image: swiftlang/swift:nightly-jammy
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: SPM Linux Test
        run: swift test -c debug
