name: Produce Release Artifacts and Bump Tap

on:
  release:
    types: [created]

jobs:
  release:
    name: Upload Release Artifact
    runs-on: self-xcode264
    env:
      DEVELOPER_DIR: /Applications/Xcode_26.4.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build for Release
        run: swift build --build-system swiftbuild -c release --arch arm64 --arch x86_64
      - name: "Strip Artifact"
        run: strip -rSTx .build/out/Products/Release/firewalk
      - name: "Zip Artifacts"
        run: zip -r ./firewalk.zip --junk-paths .build/out/Products/Release/firewalk # Add resources later.
      - name: "Generate Release URL"
        run: echo "::set-output name=upload_url::https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)/assets{?name,label}"
        id: release
      - name: "Upload Assets"
        uses: "softprops/action-gh-release@v2"
        if: github.ref_type == 'tag'
        with:
          files: firewalk.zip
        id: upload
      - name: "Bump Tap"
        uses: mislav/bump-homebrew-formula-action@v4
        env:
          COMMITTER_TOKEN: ${{ secrets.FIREWALK_DEPLOY }}
        if: "!contains(github.ref, '-')" # skip prereleases
        with:
          formula-name: firewalk
          homebrew-tap: Alamofire/homebrew-alamofire
          base-branch: master
          download-url: ${{ fromJSON(steps.upload.outputs.assets)[0].browser_download_url }}
          commit-message: Firewalk Release
